sudo: required

language: c

compiler:
  - gcc
  - clang

arch:
  packages:
    - cmake
    - boost
    
  script:
    - "cmake ."
    - "make"

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
